Category:
    fields:
        title: varchar(50)
    relations:
        Article: many

Tag:
    fields:
      name: varchar(30)
    relations:
      Article: many
      Order: many

Order:
    fields:
      name: varchar(30)
    relations:
      Category: one
      Tag: many

Article:
    fields:
        title: varchar(50)
        text: text
    relations:
        Tag: many
        Category: one

